jdbc:
  primary:
    dialect: wang.liangchen.matrix.framework.data.datasource.dialect.PostgreSQLDialect
    datasource: org.h2.jdbcx.JdbcDataSource
    url: jdbc:h2:file:./src/main/resources/matrix_db;database_to_upper=false;MODE=PostgreSQL
    username: sa
    password: password
    driverClassName: org.h2.Driver
#  pg:
#    dialect: wang.liangchen.matrix.framework.data.datasource.dialect.PostgreSQLDialect
#    datasource: com.zaxxer.hikari.HikariDataSource
#    database: matrix_db
#    schema: matrix_schema
#    host: 127.0.0.1
#    port: 5432
#    username: matrix_user
#    password: matrix_pwd